// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPAnaDpTGs1vfSS-C53QWNRdO856YqfU',
    appId: '1:220516751432:web:1b7b64f16fc6089790607d',
    messagingSenderId: '220516751432',
    projectId: 'todoapp-d020d',
    authDomain: 'todoapp-d020d.firebaseapp.com',
    storageBucket: 'todoapp-d020d.appspot.com',
    measurementId: 'G-E31WD5Z0NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0PZHxvGmGZiPR9tk_zM9In-pU8I9p-cc',
    appId: '1:220516751432:android:71244a2ba0c025d090607d',
    messagingSenderId: '220516751432',
    projectId: 'todoapp-d020d',
    storageBucket: 'todoapp-d020d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkHuKpEV7LM0K0jIT77E0JR7XDWeQ2Qms',
    appId: '1:220516751432:ios:a4e55af7ab5e71b890607d',
    messagingSenderId: '220516751432',
    projectId: 'todoapp-d020d',
    storageBucket: 'todoapp-d020d.appspot.com',
    iosBundleId: 'com.lauransenga.finalTodoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkHuKpEV7LM0K0jIT77E0JR7XDWeQ2Qms',
    appId: '1:220516751432:ios:ce9b3cd6b02a1c3e90607d',
    messagingSenderId: '220516751432',
    projectId: 'todoapp-d020d',
    storageBucket: 'todoapp-d020d.appspot.com',
    iosBundleId: 'com.lauransenga.finalTodoapp.RunnerTests',
  );
}
